### ISSUE TITLE
list of cards

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#1]
## Value statement - a requirement, not a solution
As a User 
I need a list of cards with workout pictures/illustrations
so that I become an overview of all available exercises

## Description (Text, Scribble, Wireframe, Design)
- it's a list of scrolling cards
- a card contains an illustration

## Acceptance criteria
- [ ] cards have to be visually separated
- [ ] cards are scrolled vertically 

## Tasks
- [ ] create necessary components
- [ ] all cards have the same size and gap
- [ ] styling 
- [ ] test in mobile and desktop view
## Size
M
