### ISSUE TITLE
Likes for every exercise

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#10]
## Value statement - a requirement, not a solution
As a User
I need a like icon (heart)
so that I can decide if I want this exercise in my personal workout plan

## Description (Text, Scribble, Wireframe, Design)
- like heart icon on every exercise

## Acceptance criteria
- [ ] every exercise has a like heart (on the top, right)
- [ ] on click color change
- [ ] save in local storage

## Tasks
- [ ] create a necessary component Like in Storybook
- [ ] add component in App
- [ ] styling and testing
- [ ] add local storage 

## Size
M
