### ISSUE TITLE
filter all exercises vs. liked exercises

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#11]
## Value statement - a requirement, not a solution
As a User
I need a filter function 
so that I can see only my liked exercises for an overview

## Description (Text, Scribble, Wireframe, Design)
- filter function (all exercises / liked exercises)

## Acceptance criteria
- [ ] all liked exercises should be shown if the user clicks an the filter "show only liked exercises"

## Tasks
- [ ] add component Filter in Storybook
- [ ] add component Filter in App
- [ ] styling and testing on mobile and desktop view

## Size
M
