### ISSUE TITLE
Footer : Nav

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#12]
## Value statement - a requirement, not a solution
As a User
I need a navigation bar
so that I can on what screen I am and what screens are in the App 

## Description (Text, Scribble, Wireframe, Design)
- a navigation with 4 icons: home, plus, heart and workout timer/start symbol

## Acceptance criteria
- [ ] navigation with 4 columns and 4 icons (grid)
- [ ] styling like sketch template
- [ ] should always be fixed on screen

## Tasks
- [ ] create a component Nav in Storybook
- [ ] add component Nav in App
- [ ] 4 icons as nav symbols
- [ ] styling and testing 
- [ ] color should change on what page the user is 

## Size
M
