### ISSUE TITLE
CreateWorkout form => second screen

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#19]
## Value statement - a requirement, not a solution
As a User
I need a form with input fields
so that I can create an individual workout

## Description (Text, Scribble, Wireframe, Design)
- form with input fields:
- name of workout
- category (checkbox)
- list of liked exercises (with checkbox)
- evtl. Intervall??

## Acceptance criteria
- [ ] input field: Name des Workouts
- [ ] checkboxes: Kraft, Cardio, Yoga
- [ ] list of liked exercises with checkbox 
- [ ] optional: intervall time (workout / pause)

## Tasks
- [ ] create a necessary component CreateWorkout in Storybook
- [ ] add component in App
- [ ] styling and testing

## Size
M
