### ISSUE TITLE
show description of exercise

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#2]
## Value statement - a requirement, not a solution
As a User 
I need a short description of every exercise
so that I can decide if I want to give this exercise a like 

## Description (Text, Scribble, Wireframe, Design)
- by click on the button is a short description of this exercise shown

## Acceptance criteria
- [ ] description is hidden by default
- [ ] button icon changes on tap
- [ ] the other cards don't change their position

## Tasks
- [ ] Add toggle logic
- [ ] finish styling
- [ ] test on mobile and desktop

## Size
M
