### ISSUE TITLE
add button 

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#3]
## Value statement - a requirement, not a solution
As a User 
I need a button
so that I can see a short description text

## Description (Text, Scribble, Wireframe, Design)
There will be a button (icon show description resp. hide description) 

## Acceptance criteria
- [ ] description is hidden by default
- [ ] button with changing icons on tap (show and hide)

## Tasks
- [ ] create button component for every card
- [ ] with changing icons
- [ ] finish styling

## Size
S
