### ISSUE TITLE
add delete function for created individual workout

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#33]
## Value statement 
As a User 
I need a delete function
so that I can be flexible and have the opportunity to delete my created workout

## Description (Text, Scribble, Wireframe, Design)
- x in every created workout on the third screen (favorites)

## Acceptance criteria
- [ ] x on image of exercise (right & top)
- [ ] delete function
- [ ] on click: pop up, to check if the user really wants to delete (ja oder nein)

## Tasks
- [ ] add a x button with a delete function
- [ ] pop-up 

## Size
S
