### ISSUE TITLE
Add delete to favorites screen

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#35]
## Value statement 
As a User  
I need a delete option 
so that I can delete my individual created workout.

## Description (Text, Scribble, Wireframe, Design)
- delete "x" on every workout in my workout overview

## Acceptance criteria
- [ ] "x" on every workout card
- [ ] add delete function 

## Tasks
- [ ] testing mobile and desktop
- [ ] delete in backend

## Size
M
