### ISSUE TITLE
search filter on home screen

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#36]
## Value statement - a requirement, not a solution
As a User
I need a search function
so that I can find my exercise easier by a search bar.

## Description (Text, Scribble, Wireframe, Design)
- on first screen integrate in header a search bar

## Acceptance criteria
- [ ] search bar in header on first screen
- [ ] fuzzy search 

## Tasks
- [ ] add a necessary component SearchFilter 
- [ ] testing mobile and in desktop view

## Size
M
