### ISSUE TITLE
create pictures of exercises

### ISSUE THREAD

**Issue by mariniem** [mariniem/capstone-project#4]
## Value statement 
As a User
I need pictures of exercises
so that I can see an overview of all available exercises

## Description (Text, Scribble, Wireframe, Design)
- 

## Acceptance criteria
- [ ] add about 12 images/illustrations

## Tasks
- [ ] search or produce pictures / illustrations of different exercises
- [ ] give every exercise a title and a short description in .json file

## Size
(small, medium, large)
